# Generated by Django 5.1 on 2025-11-25 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_quotes_alter_post_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='quotes',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
